### ISSUE TITLE
Unable to install pwpush

### ISSUE THREAD

**Issue by apperrault** [pglombardo/pwpush-cli#436]
## 🐛 Bug Report

When I run pip install pwpush I get the following error,  ERROR: Could not find a version that satisfies the requirement pwpush (from versions: none)

## 🔬 How To Reproduce

1. run pip install pwpush

### Code sample

NONE

### Environment

* OS: Linux
* Python version, get it with:

Python 3.6.8

## 📈 Expected behavior

i expected it to install pwpush

**Comment by pglombardo** [comment]
Hi @apperrault - try adding `--pre` to the pip install command line:

`pip install --pre pwpush`

I'm hoping to get this package out of development/beta sometime soon.  This should resolve it though.  Let me know if not.

**Comment by apperrault** [comment]
same thing.  its really odd.

![image](https://user-images.githubusercontent.com/5666402/211910272-db790e8a-ee20-43c8-b7f0-f31e47095224.png)

**Comment by pglombardo** [comment]
Apologies that I didn't remember this initially.  The package requires Python 3.7 or greater.

I tried Python 3.6 here locally and got the same result.  Works with Python 3.7-10.

**Comment by apperrault** [comment]
that would do it.  I will update it and test it out.

thanks

**Comment by apperrault** [comment]
I wanted to let you know that worked.  Thanks

**Comment by pglombardo** [comment]
Excellent - if you have any troubles, let me know.  It's still in rough pre beta but functional.
